# https://home.miot-spec.com/spec/mmgg.feeder.fi1
# TODO: Currently only supports displaying 5 programmed feed plans instead of the full 10
# TODO: Currently only supports displaying programmed feed plans in raw form
external_components:
  source: github://dhewg/esphome-miot@main

substitutions:
  # "Dispense Food" button portions (1 ~ 30).
  dispense_food_portions: "1"

esphome:
  name: feeder
  friendly_name: Pet Feeder
  comment: Xiaomi Smart Pet Food Feeder (mmgg.feeder.fi1)
  project:
    name: "dhewg.esphome-miot"
    version: "mmgg.feeder.fi1"

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: GMT0

esp8266:
  board: esp_wroom_02

logger:
  level: VERBOSE
  # Important: Disable UART1 logging to avoid hardware errors on main UART0
  baud_rate: 0

api:
  encryption:
    key: !secret feeder_api_key
  reboot_timeout: 0s
  on_client_connected:
    then:
      # Refresh the feed plan when HA connects
      - lambda: id(miot_main).execute_action(5, 6, "11 0");
  services:
    # DEBUG ONLY: Send **arbitrary commands** to MCU from HA
    - service: mcu_command
      variables:
        command: string
      then:
        - lambda: id(miot_main).queue_command(command);
    # Refresh the "Raw Feed Plan" sensor on demand
    - service: refresh_feed_plan
      then:
        - lambda: id(miot_main).execute_action(5, 6, "11 0");
    # Dispense the specified amount of portions
    - service: dispense_food
      variables:
        portions: int
      then:
        - lambda: id(miot_main).queue_command("action 2 1 5 %i", portions);
    # Add a new scheduled feeding time to MCU memory
    - service: add_scheduled_feed
      variables:
        id: int
        hour: int
        minute: int
        portions: int
      then:
        - lambda: |
            id(miot_main).queue_command(
              "action 5 7 10 %i 6 %i 7 %i 8 %i",
              id, hour, minute, portions);
        # Manually refresh the feed plan afterwards
        - lambda: id(miot_main).execute_action(5, 6, "11 0");
    # Edit a scheduled feeding time in MCU memory
    - service: edit_scheduled_feed
      variables:
        id: int
        hour: int
        minute: int
        portions: int
      then:
        - lambda: |
            id(miot_main).queue_command(
              "action 5 8 10 %i 6 %i 7 %i 8 %i",
              id, hour, minute, portions);
        # Manually refresh the feed plan afterwards
        - lambda: id(miot_main).execute_action(5, 6, "11 0");
    # Remove a scheduled feeding time from MCU memory
    - service: remove_scheduled_feed
      variables:
        id: int
      then:
        - lambda: id(miot_main).queue_command("action 5 9 10 %i", id);
        # Manually refresh the feed plan afterwards
        - lambda: id(miot_main).execute_action(5, 6, "11 0");

ota:
  password: !secret feeder_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Pet-Feeder Fallback Hotspot"
    password: !secret feeder_ap_password

captive_portal:
    
uart:
  tx_pin: GPIO15
  rx_pin: GPIO13
  baud_rate: 115200

miot:
  id: miot_main

switch:
  - platform: "miot"
    miot_siid: 3
    miot_piid: 1
    miot_true: "1"
    miot_false: "0"
    name: "Indicator Lights"
    icon: mdi:lightbulb
    entity_category: config
  - platform: "miot"
    miot_siid: 5
    miot_piid: 5
    miot_true: "1"
    miot_false: "0"
    name: "Feeding Schedule"
    icon: mdi:calendar-badge
    entity_category: config
  - platform: "miot"
    miot_siid: 6
    miot_piid: 1
    miot_true: "1"
    miot_false: "0"
    name: "Child Lock"
    icon: mdi:lock
    inverted: yes
    entity_category: config

binary_sensor:
  - platform: "miot"
    miot_siid: 4
    miot_piid: 8
    miot_true: "1"
    miot_false: "0"
    name: "Top Lid"
    device_class: opening
  - platform: "miot"
    miot_siid: 4
    miot_piid: 9
    miot_true: "1"
    miot_false: "0"
    name: "Food Door"
    device_class: opening

text_sensor:
  - platform: "miot"
    miot_siid: 2
    miot_piid: 1
    name: "Faults"
    icon: mdi:chili-alert
    entity_category: diagnostic
    filters:
      - map:
        - "0 -> No Faults"
        - "1 -> OK"
        - "3 -> Error"
        - "5 -> Timeout"
  - platform: "miot"
    miot_siid: 2
    miot_piid: 6
    name: "Food Level"
    icon: mdi:cup
    filters:
      - map:
        - "0 -> Normal"
        - "1 -> Low"
        - "2 -> Empty"
  - platform: "miot"
    miot_siid: 4
    miot_piid: 5
    name: "Last Feed Source"
    icon: mdi:food-apple
    miot_poll: false
    filters:
      - map:
        - "0 -> Schedule 0"
        - "1 -> Schedule 1"
        - "2 -> Schedule 2"
        - "3 -> Schedule 3"
        - "4 -> Schedule 4"
        - "5 -> Schedule 5"
        - "6 -> Schedule 6"
        - "7 -> Schedule 7"
        - "8 -> Schedule 8"
        - "9 -> Schedule 9"
        - "255 -> Manual Feed"
  # FeedID,Hour,Minute,Portions,(Dispensed=0,Pending=255) x5
  - platform: "miot"
    miot_siid: 5
    miot_piid: 12
    miot_poll: false
    name: "Raw Feed Plan"
    entity_category: diagnostic
    icon: mdi:calendar

number:
  - platform: "miot"    
    miot_siid: 9
    miot_piid: 12
    name: "Phone Timezone"
    icon: mdi:clock
    entity_category: config
    step: 1
    min_value: -12
    max_value: 12
  - platform: "miot"    
    miot_siid: 9
    miot_piid: 13
    name: "Device Country"
    icon: mdi:clock
    entity_category: config
    step: 1
    min_value: 0
    max_value: 255

sensor:
  - platform: "miot"
    miot_siid: 4
    miot_piid: 4
    name: "Last Feed Portions"
    icon: mdi:food-apple
    miot_poll: false
  - platform: "miot"
    miot_siid: 8
    miot_piid: 1
    name: "Feeder Clean Timer"
    unit_of_measurement: days
    icon: mdi:broom
  - platform: "miot"
    miot_siid: 11
    miot_piid: 2
    name: "Dessicant Replace Timer"
    unit_of_measurement: days
    icon: mdi:air-filter

button:
  - platform: "miot"
    miot_siid: 2
    miot_aiid: 1
    miot_action_args: '5 ${dispense_food_portions}'
    name: "Dispense Food"
    icon: mdi:food-apple
  - platform: "miot"
    miot_siid: 8
    miot_aiid: 1
    name: "Reset Clean Timer"
    icon: mdi:restart
  - platform: "miot"
    miot_siid: 11
    miot_aiid: 1
    name: "Reset Dessicant Timer"
    icon: mdi:restart